version: '3'

services:
  app:
    image: traefik
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    networks:
      - web

networks:
  web:
    external: true
    
