version: '3'
services:
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    volumes:
     - ./gogs-data:/data
    ports:
     - "10022:22"
    restart: always
    labels:
     - "traefik.enable=true"
     - "traefik.backend=gogs"
     - "traefik.docker.network=web"
     - "traefik.frontend.rule=Host:gogs.glukoo.si"
     - "traefik.port=3000"
    networks:
     - web

networks:
  web:
    external: true
